Bash/Zsh Completion対応
dondakeshimo/todo-cli pull request #32
Opened 2020-12-06 04:05 UTC by dondakeshimo

# チケット

# 概要

2020-12-06 04:20 UTC, dondakeshimo commented
@IkuyaYamada 
特に英語のレビューお願い笑

2020-12-06 04:45 UTC, IkuyaYamada commented
```
PROG=todo
_CLI_ZSH_AUTOCOMPLETE_HACK=1
source path/to/todo-cli/scripts/zsh_autocomplete
```

をしてみたけど、

```
	$ todo 2020/12/06 13:44:23 flag provided but not defined: -generate-bash-completion                                         [feature/SlackNotification]
          todo                                                                                                                      [feature/SlackNotification]
   --help, -h     show help (default                                                                                                                        
   --version, -v  print the version (default                                    --  false)                                                                    
GLOBAL OPTIONS                                  COMMANDS  VERSION  USAGE  NAME  --                                                                            
Incorrect Usage. flag provided but not defined                                  --  -generate-bash-completion                                                 
                                help, h    Shows a list of commands or help for one command      todo - Manage Your TODO                                      
   0.0.1                        list, l    List tasks                                            todo [global options] command [command options] [arguments...]
   add, a     Add a task        modify, m  Modify a task                                                                                                      
   close, c   Close a task      notify     Notify a task (basicaly be used by system)                                                                         
```

また違った感じのメッセージが表示されてしまう

2020-12-06 04:49 UTC, IkuyaYamada requested changes
ほぼ良さそう

2020-12-06 04:49 UTC, IkuyaYamada commented on README.md
> +ZSH completion would often shows inappropriate candidates
would often shows  -> may show  くらいかな

2020-12-06 04:49 UTC, IkuyaYamada commented on README.md
> +We recommend you to set zsh-completion configuration.
We recommend that you set zsh-completion configuration.

2020-12-06 05:03 UTC, dondakeshimo commented
> また違った感じのメッセージが表示されてしまう

todo-cliのこのbranchをpullした後に再インストールかビルドしたものを使っただろうか？

2020-12-12 06:33 UTC, IkuyaYamada approved these changes
Good

2020-12-12 08:37 UTC, merged